# Cours 1 : Rappels Python + Analyse et retraitement de la donné

## 1. Préambule

L'objectif de cette séance (3h) est de construire une base de données propre pour la modélisation, tout en analysant les caractéristiques du portefeuille.

# Rappels Python

### Numériques, calculs élémentaires et imports

In [75]:
print(3+4)
print(5*2.5)
print(int)
print(float)
a=2**90
print(a)
print(type(a))

7
12.5
<class 'int'>
<class 'float'>
1237940039285380274899124224
<class 'int'>

In [76]:
import math

import pandas as pd

#from math import *
#help(math)
print (math.sqrt(3))
print (math.floor(3.2))
print (math.cos(math.pi/3.0))

1.7320508075688772
3
0.5000000000000001

### Chaine de caractères

In [77]:
print('33' + "42")
a="toto est toto"
a[4:]
#Tout est objet
print(a.split(' '))

3342
['toto', 'est', 'toto']

In [78]:
salutation = "Bonjour, monsieur {}. Comment allez vous en ce {}?".format("XX", "Mardi 19 septembre")
print(salutation)

Bonjour, monsieur XX. Comment allez vous en ce Mardi 19 septembre?

In [79]:
len("toto")

4

### Les listes

In [80]:
a = [1,'q',2,3,5,8,'TOTO']
print (a[1])
print (a[-1])
print (a[1:3])
print (a[-4:-2])
print([5]*4)

q
TOTO
['q', 2]
[3, 5]
[5, 5, 5, 5]

In [81]:
print (range(4, 10))
print (range(5, 50, 3))
print ([3,1,4] + [1,5,9])
print (len(range(4, 10)))

range(4, 10)
range(5, 50, 3)
[3, 1, 4, 1, 5, 9]
6

### Les tests

In [82]:
a = 2
if 5 > a:
    print ("Cinq!")
else:
    print ("a!")

#Zoom sur indentation
num=3
if num == 1:
    print ("C'est 1")
elif num == 2:
    print ("C'est 2")
elif num == 3:
    print ("C'est 3")
else :
    print ("Autre que 1, 2 et 3")

print(num in [1,2,3])
print(num not in [1,2,3])
print(num != 5)

print(num in [1,2,3] and num >0)

print(not 5==3)

Cinq!
C'est 3
True
False
True
True
True

### Les boucles

In [83]:
a=[3,4,5]
#Boucle for
for i in range(len(a)):
    a[i] += 3
print (a)
%timeit for i in range(len(a)):a[i] += 3
print (a)

b=[3,4,5]
print([i+3 for i in b])
%timeit [i+3 for i in b]
print (b)

for i,item in enumerate(b):
    print(i,item)

[6, 7, 8]
172 ns ± 55.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
[24333339, 24333340, 24333341]
[6, 7, 8]
84.7 ns ± 3.38 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
[3, 4, 5]
0 3
1 4
2 5

In [84]:
#Boucle While , break et continue
print("démarrage boucle")
i=0
while i<100:
    print(i)
    i+=1
    if i==52:
        i+=10
        print("increment de 10")
        continue
    i+=2
    if i ==77:
        break

démarrage boucle
0
3
6
9
12
15
18
21
24
27
30
33
36
39
42
45
48
51
increment de 10
62
65
68
71
74

### Les fonctions

In [85]:
def square(x):
    return x*x
print (square(3))

9

### Pandas - Gestion de DataFrame

Les principales possibilités de cette librairie sont :

- __récupérer des données__ depuis des fichiers CSV, tableaux Excel, des pages web, etc. ;
- grouper, découper, alléger, déplacer, écrire les données sous forme de __DataFrame__, tracer des graphiques simplifiés ;
- ces données peuvent être à une ou deux dimensions, ou encore temporelles avec ou sans périodicité.

Le développement de cette bibliothèque s'inscrit dans la problématique de disposer d'outils pour **manipuler de gros volumes de données dans le but de leur exploitation scientifique ou commerciale**.

####  Series

Le type de base dans Pandas est la série. Une série est un vecteur de valeurs de variables.

1. Importer **la librairie pandas** et créer **une série contenant la suite des chiffres de 1 à 5 et des index alphabétiques de "a" à "e"**. 
2. **Afficher cette série.**
3. **Afficher ses index.**
4. **Afficher sa moyenne.**
5. **Afficher la valeur de l'index "b" de cette série**

In [86]:
#Ecrivez votre code ici

serie = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5})

print(serie)
print(serie.index)
print(serie.mean())
print(serie['b'])
print(serie.b)

a    1
b    2
c    3
d    4
e    5
dtype: int64
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
3.0
2
2

#### Dataframes

Le dataframe est l’**extension en 2 dimensions des series**. Il peut être vu comme un empilement de series dont les index sont partagés (et donc intrinsèquement alignés), ou comme dans un tableur où les index sont les numéros de lignes et les noms des series les noms des colonnes.

Un dataframe se comporte comme un dictionnaire dont les cléss sont les noms des colonnes et les valeurs sont des series.
On peut créer un dataframe à partir de dictionnaires, de liste de listes ou de liste de series, d’arrays numpy, de fichier Excel ou CSV, depuis des bases de données, …

6. Créer **deux séries s et t** contenant **un échantillon de 4 valeurs issues d'une loi normale centrée réduite** et ayant pour **index** :
    - **1, 2, 3, 5 pour s**
    - **1, 2, 3, 4 pour t**

Afficher ces séries.

In [87]:
from numpy.random import standard_normal

s = pd.Series(standard_normal(size=4), index=[1, 2, 3, 5])

t = pd.Series(standard_normal(size=4), index=[1, 2, 3, 4])

print(s, t)

1    0.637553
2    1.280335
3   -0.488665
5    1.361516
dtype: float64 1   -0.631333
2   -0.312044
3   -0.909777
4   -0.493984
dtype: float64

7. Créer **une dataframe** contenant **les deux séries, avec leur nom pour noms de colonnes.** L'afficher.

In [88]:
#Ecrivez votre code ici
df = pd.DataFrame({
    's': s,
    't': t
})

print(df)

          s         t
1  0.637553 -0.631333
2  1.280335 -0.312044
3 -0.488665 -0.909777
4       NaN -0.493984
5  1.361516       NaN

8. **Les opérations sur une DataFrame :**

Créer **une nouvelle colonne "SUM**", ayant pour valeur **la somme des deux séries ligne à ligne**. Afficher la DataFrame.

In [89]:
#Ecrivez votre code ici
df['SUM'] = df['s'] + df['t']

print(df)

          s         t       SUM
1  0.637553 -0.631333  0.006220
2  1.280335 -0.312044  0.968291
3 -0.488665 -0.909777 -1.398441
4       NaN -0.493984       NaN
5  1.361516       NaN       NaN

9. Afficher la moyenne de la colonne "SUM".

In [90]:
#Ecrivez votre code ici
print(df['SUM'].mean())

-0.14131029153083904

### La bibliothèque NumPy

**La bibliothèque NumPy permet d’effectuer des calculs numériques avec Python. Elle introduit une gestion facilitée des tableaux de nombres.**

Pour info : Pandas ou Numpy ? Dans le cas de Pandas, ce ne sont pas tout-à-fait des matrices mais des tables de données : la même table peut contenir différents types de données, des nombres, des chaînes de caractères, des booléens, des dates… Les données se manipulent comme des bases de données et les Dataframe de pandas sont optimisées pour ça. Chaque colonne porte un nom. Numpy propose des matrices à une ou plusieurs dimensions optimisées pour le calcul matriciel. Ces matrices ne contiennent que des nombres et tous du même type.

**--> Pour faire des calculs matriciels, on choisit numpy. Pour faire de la gestion de base de données telle qu'une jointure de table, on choisit pandas.**

10. A l'aide de la librairie Numpy, générer **un échantillon issu d'une loi normale centrée réduite de 250 valeurs**. L'**afficher**.
11. Créer **une série contenant l'échantillon précédent**. Les **index** de cette série consisteront en **un historique journalier à compter du 01/01/2012** (*indice : pour la définition des index, utiliser la fonction date_range de pandas*). **Afficher cette série**.
12. Importer la **fonction offsets de pandas** et créer **une nouvelle range d'index** en repartant de la range d'index précédente mais en sélectionnant **un jour sur deux**. **Afficher cette range d'index**.

In [91]:
#Ecrivez votre code ici
import numpy as np

X = np.random.standard_normal(size=250)

print(X)
print(X.size)

[-9.76660279e-01 -1.72139343e-01 -6.45412326e-01  6.43525711e-01
 -2.21718155e-02 -1.72162893e+00 -1.92327652e+00 -1.21101350e+00
 -2.36972484e-01 -7.26908700e-01 -9.89004283e-01 -8.57713592e-01
  1.51813146e-01 -1.26909661e+00  8.36575528e-01 -1.24419906e+00
  3.42013990e-01  7.60586175e-01 -7.31467826e-01  9.25350696e-01
  2.68683670e-01 -3.81297445e-02  7.84379544e-02  8.66147819e-01
 -4.71094918e-02  4.94394308e-02  3.76856196e-02  2.46035297e-02
  1.16591068e+00  4.46108470e-01 -1.84096965e+00  9.70091766e-02
  4.33689026e-01 -2.69970195e-01 -2.71437619e-01 -1.74036888e+00
  7.80974246e-01  1.56440090e+00 -2.07795230e+00  6.78391627e-01
 -7.85222002e-01 -7.27273758e-01  2.28199931e+00  1.37483945e-02
 -8.94904731e-01  1.19284461e+00  1.45818302e-01  1.02331451e-01
  1.71523821e+00 -6.00926005e-01  4.09617897e-01 -1.24493168e-02
  1.69631598e+00 -1.32408741e+00  4.80298442e-01 -9.74731944e-01
 -9.87270715e-01 -5.26948200e-01 -2.23103987e-01  5.67133627e-01
  8.86664938e-03  4.25261224e-01  1.11543702e-01 -1.29584901e+00
  5.28299182e-01 -3.26345306e-01  1.63565603e+00 -4.51341303e-01
  7.80714273e-01 -6.82694544e-02  1.64632279e-01 -1.10553110e+00
 -1.02218188e+00  2.03561784e-01 -1.28638219e+00 -1.54757966e+00
  6.85758824e-01 -5.88174649e-01 -2.96147856e+00 -1.76530766e+00
 -1.30015279e+00  1.57012637e+00  8.16924987e-01 -1.23228054e-01
 -6.81715901e-01 -1.84728033e-01 -5.93623898e-01  2.26367620e-01
 -9.60960737e-01  1.10566362e+00 -1.15303078e-01  4.92544922e-01
 -2.49880990e-01  1.03063491e-01 -5.23301955e-01  5.52926598e-01
 -2.94960534e-01 -6.52052475e-01  8.43152956e-01 -1.02561075e+00
  1.46202182e+00  2.06312642e+00  8.23555520e-01  6.15182380e-01
 -3.90719695e-01 -1.12104014e+00 -1.35371492e-01 -1.36606509e+00
 -1.38943353e+00 -1.45046260e-01 -1.18937372e-01 -8.14179108e-01
  1.76070510e-03 -6.51054374e-01  4.47518754e-01  1.17832003e+00
 -1.36000223e+00 -2.11849300e-02 -1.41864457e+00  6.09263286e-01
 -1.88745302e-01  4.09437004e-01 -4.39252371e-01  9.14842234e-01
 -1.18431343e+00 -7.69414079e-01  4.81346439e-01 -3.58843245e-02
  9.44853538e-01 -4.52721653e-02  1.45830160e-01  1.36014889e+00
 -2.30124050e+00 -5.78123102e-01  1.65124424e-01 -2.60071571e-01
 -5.92053747e-01  1.67138899e+00  1.51129597e+00 -1.46142027e+00
 -8.21905300e-01 -2.65516694e-01 -8.20751930e-01 -3.76213675e-01
 -1.38018133e+00  3.86845551e-01 -3.07304224e-02  3.73685988e-01
 -2.96592844e-01  1.62591892e+00  8.22937555e-01  1.28378644e-01
  1.30363087e+00 -1.22319706e+00 -1.52558361e+00 -3.60527187e-01
 -1.95963267e-01  8.31387326e-02 -1.61987762e-01  5.73126235e-01
 -5.76802581e-01 -1.84916862e-01 -7.72078906e-01 -9.74666165e-02
  1.28974683e-02 -1.13951435e+00  7.19148081e-01 -9.34996488e-01
 -6.63263578e-01  4.83430459e-01 -1.92474342e+00 -4.92747990e-02
  1.82598161e-01 -3.85737844e-01 -6.83880812e-01  5.40510689e-01
  4.85759681e-01  9.13033916e-01  6.19182579e-01 -1.61239128e+00
 -5.22639783e-01 -1.12112655e+00 -1.55754244e+00  6.19535974e-01
 -7.73501604e-01 -9.91652917e-01 -1.07571737e-01  7.09467033e-01
 -8.99234441e-01 -6.60510953e-01 -3.04843885e-01  6.39058426e-01
  4.39610907e-01 -1.56635457e-01 -2.85160873e-01 -1.29968622e+00
  6.30447500e-01  3.86604402e-01 -1.42542111e+00  1.15195194e-01
 -7.55713888e-01 -8.47368743e-01  8.91623520e-01 -8.49671215e-01
  8.19177944e-01 -1.14893014e+00 -9.63812737e-02 -7.25642587e-01
 -8.35448015e-01  4.59979103e-01  5.55444709e-01  3.62808195e-01
 -1.73764181e+00  1.36305628e+00  1.40350847e+00 -1.06295501e+00
 -6.52917175e-01 -7.49405607e-02 -1.29792942e-01  3.40030940e-01
  4.17410764e-01  7.89271497e-01  1.27604781e+00  8.77602551e-01
  3.12819095e-01 -9.52432040e-01  1.41955522e+00 -5.84620129e-02
  8.78032870e-01 -2.11992885e+00  3.17000937e-01 -3.21286430e-01
  9.70549042e-01 -4.61179605e-01 -1.26069149e+00  9.75155020e-01
 -1.35485580e+00  1.05294057e+00 -1.92239795e+00  9.42112017e-02
  4.95628780e-01 -1.88547562e+00 -5.18314211e-01 -8.55296968e-01
  4.76259689e-01 -1.29699356e+00  8.45634977e-01 -4.97421053e-01
  5.84654224e-02 -7.88074809e-01]
250

In [92]:
index = pd.date_range('2012-01-01', periods=250, freq='D')

serie = pd.Series(X, index=index)
print(serie)

2012-01-01   -0.976660
2012-01-02   -0.172139
2012-01-03   -0.645412
2012-01-04    0.643526
2012-01-05   -0.022172
                ...
2012-09-02   -1.296994
2012-09-03    0.845635
2012-09-04   -0.497421
2012-09-05    0.058465
2012-09-06   -0.788075
Freq: D, Length: 250, dtype: float64

In [93]:
new_index = index[::2]
print(new_index)

DatetimeIndex(['2012-01-01', '2012-01-03', '2012-01-05', '2012-01-07',
               '2012-01-09', '2012-01-11', '2012-01-13', '2012-01-15',
               '2012-01-17', '2012-01-19',
               ...
               '2012-08-18', '2012-08-20', '2012-08-22', '2012-08-24',
               '2012-08-26', '2012-08-28', '2012-08-30', '2012-09-01',
               '2012-09-03', '2012-09-05'],
              dtype='datetime64[ns]', length=125, freq='2D')

# Travail pratique

## 3. Préparation du workspace

### Import de librairies

In [94]:
#Data frame
import pandas as pd
import plotly.express as px
import plotly.graph_objects as gp
import seaborn as sns

sns.set()

### Constantes

In [95]:
input_path = "./1_inputs"
output_path = "./2_outputs"

## 4. Import et visualisation des données

### Import des données

In [96]:
path =input_path + '/base_modelisation.csv'
data_set = pd.read_csv(path,sep=";",decimal=",")

### Une première observation des données

In [97]:
# Premières lignes
data_set.head()

,ANNEE_CTR,CONTRAT_ANCIENNETE,FREQUENCE_PAIEMENT_COTISATION,GROUPE_KM,ZONE_RISQUE,AGE_ASSURE_PRINCIPAL,GENRE,DEUXIEME_CONDUCTEUR,ANCIENNETE_PERMIS,ANNEE_CONSTRUCTION,ENERGIE,EQUIPEMENT_SECURITE,PUISSANCE_VEHICULE,VALEUR_DU_BIEN,NB,CHARGE,EXPO
0,2019,"(-1,0]",ANNUEL,[20000;40000[,B,54,M,False,47,2016.0,ESSENCE,FAUX,NaN,[10000;15000[,0,0.0,0.672131
1,2019,"(-1,0]",ANNUEL,[20000;40000[,B,88,F,True,55,2018.0,DIESEL,VRAI,"(85,96]",[20000;25000[,0,0.0,0.631148
2,2021,"(1,2]",ANNUEL,[0;20000[,D,35,F,True,16,2017.0,ESSENCE,FAUX,"(74,80]",[15000;20000[,0,0.0,0.821918
3,2021,"(2,5]",ANNUEL,[0;20000[,C,46,NaN,False,44,2018.0,ESSENCE,VRAI,"(120,596]",[35000;99999[,0,0.0,0.832877
4,2018,"(2,5]",MENSUEL,[20000;40000[,A,46,F,False,31,2009.0,DIESEL,FAUX,"(66,74]",[10000;15000[,0,0.0,1.000000

In [98]:
# Dernières lignes
data_set.tail()

,ANNEE_CTR,CONTRAT_ANCIENNETE,FREQUENCE_PAIEMENT_COTISATION,GROUPE_KM,ZONE_RISQUE,AGE_ASSURE_PRINCIPAL,GENRE,DEUXIEME_CONDUCTEUR,ANCIENNETE_PERMIS,ANNEE_CONSTRUCTION,ENERGIE,EQUIPEMENT_SECURITE,PUISSANCE_VEHICULE,VALEUR_DU_BIEN,NB,CHARGE,EXPO
14259,2021,"(2,5]",MENSUEL,[0;20000[,D,55,M,False,49,2017.0,ESSENCE,FAUX,"(80,85]",[20000;25000[,0,0.0,0.495890
14260,2019,"(2,5]",MENSUEL,[20000;40000[,A,33,NaN,False,14,2017.0,ESSENCE,FAUX,"(1,51]",[10000;15000[,0,0.0,0.999094
14261,2017,"(-1,0]",ANNUEL,[0;20000[,A,62,NaN,False,58,2017.0,ESSENCE,VRAI,NaN,[10000;15000[,0,0.0,0.498630
14262,2018,"(-1,0]",TRIMESTRIEL,[20000;40000[,D,20,NaN,False,7,2016.0,DIESEL,FAUX,"(105,120]",[25000;35000[,0,0.0,0.024658
14263,2017,"(-1,0]",ANNUEL,[0;20000[,C,73,F,False,41,2017.0,ESSENCE,FAUX,"(1,51]",[10000;15000[,0,0.0,0.142466

In [99]:
# Synthèse des variables
data_set.describe(include="all")

,ANNEE_CTR,CONTRAT_ANCIENNETE,FREQUENCE_PAIEMENT_COTISATION,GROUPE_KM,ZONE_RISQUE,AGE_ASSURE_PRINCIPAL,GENRE,DEUXIEME_CONDUCTEUR,ANCIENNETE_PERMIS,ANNEE_CONSTRUCTION,ENERGIE,EQUIPEMENT_SECURITE,PUISSANCE_VEHICULE,VALEUR_DU_BIEN,NB,CHARGE,EXPO
count,14264.000000,14264,14264,14261,14263,14264.000000,13522,13617,14264.000000,14058.000000,14264,14264,12089,14058,14264.000000,14264.000000,14264.000000
unique,NaN,5,3,4,17,NaN,2,2,NaN,NaN,3,2,10,6,NaN,NaN,NaN
top,NaN,"(0,1]",MENSUEL,[0;20000[,C,NaN,M,False,NaN,NaN,ESSENCE,FAUX,"(80,85]",[10000;15000[,NaN,NaN,NaN
freq,NaN,4183,6867,7665,4876,NaN,7659,10601,NaN,NaN,7312,9407,1960,3433,NaN,NaN,NaN
mean,2018.768087,NaN,NaN,NaN,NaN,44.965648,NaN,NaN,36.297602,2015.382202,NaN,NaN,NaN,NaN,0.060993,368.819292,0.757784
std,1.656104,NaN,NaN,NaN,NaN,13.685578,NaN,NaN,18.913731,3.532906,NaN,NaN,NaN,NaN,0.251886,2033.092340,0.297270
min,2016.000000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN,0.000000,1961.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,0.002732
25%,2017.000000,NaN,NaN,NaN,NaN,35.000000,NaN,NaN,19.000000,2014.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,0.561644
50%,2019.000000,NaN,NaN,NaN,NaN,44.000000,NaN,NaN,35.000000,2016.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,0.841096
75%,2020.000000,NaN,NaN,NaN,NaN,54.000000,NaN,NaN,53.000000,2017.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000
max,2021.000000,NaN,NaN,NaN,NaN,94.000000,NaN,NaN,70.000000,2021.000000,NaN,NaN,NaN,NaN,3.000000,83421.850000,1.000000

In [100]:
#Dimensions
data_set.shape

(14264, 17)

In [101]:
# Liste des colonnes
data_set.columns

Index(['ANNEE_CTR', 'CONTRAT_ANCIENNETE', 'FREQUENCE_PAIEMENT_COTISATION',
       'GROUPE_KM', 'ZONE_RISQUE', 'AGE_ASSURE_PRINCIPAL', 'GENRE',
       'DEUXIEME_CONDUCTEUR', 'ANCIENNETE_PERMIS', 'ANNEE_CONSTRUCTION',
       'ENERGIE', 'EQUIPEMENT_SECURITE', 'PUISSANCE_VEHICULE',
       'VALEUR_DU_BIEN', 'NB', 'CHARGE', 'EXPO'],
      dtype='object')

In [102]:
#Liste des colonnes selon leur type
data_set.dtypes

ANNEE_CTR                          int64
CONTRAT_ANCIENNETE                object
FREQUENCE_PAIEMENT_COTISATION     object
GROUPE_KM                         object
ZONE_RISQUE                       object
AGE_ASSURE_PRINCIPAL               int64
GENRE                             object
DEUXIEME_CONDUCTEUR               object
ANCIENNETE_PERMIS                  int64
ANNEE_CONSTRUCTION               float64
ENERGIE                           object
EQUIPEMENT_SECURITE               object
PUISSANCE_VEHICULE                object
VALEUR_DU_BIEN                    object
NB                                 int64
CHARGE                           float64
EXPO                             float64
dtype: object

**Exercice :**
Ecrire un programme qui sépare les variables selon leur type (variables quantitatives, catégorielles et binaires). Pensez à identifier les variables avec des valeurs manquantes

In [103]:
#Ecrivez votre code ici
quantitatives = []
categorielles = []
binaires = []

for col in data_set.columns:
    if data_set[col].dtype in ['int64', 'float64']:
        if len(data_set[col].dropna().unique()) == 2:
            binaires.append(col)
        else:
            quantitatives.append(col)
    else:
        if len(data_set[col].dropna().unique()) == 2:
            binaires.append(col)
        else:
            categorielles.append(col)

print("Variables quantitatives :", quantitatives)
print("\nVariables catégorielles :", categorielles)
print("\nVariables binaires :", binaires)

Variables quantitatives : ['ANNEE_CTR', 'AGE_ASSURE_PRINCIPAL', 'ANCIENNETE_PERMIS', 'ANNEE_CONSTRUCTION', 'NB', 'CHARGE', 'EXPO']

Variables catégorielles : ['CONTRAT_ANCIENNETE', 'FREQUENCE_PAIEMENT_COTISATION', 'GROUPE_KM', 'ZONE_RISQUE', 'ENERGIE', 'PUISSANCE_VEHICULE', 'VALEUR_DU_BIEN']

Variables binaires : ['GENRE', 'DEUXIEME_CONDUCTEUR', 'EQUIPEMENT_SECURITE']

In [104]:
#Ecrivez votre code ici
variables_avec_na = []

for col in data_set.columns:
    if data_set[col].isnull().any():
        variables_avec_na.append(col)

print("\nVariables avec valeurs manquantes :", variables_avec_na)

Variables avec valeurs manquantes : ['GROUPE_KM', 'ZONE_RISQUE', 'GENRE', 'DEUXIEME_CONDUCTEUR', 'ANNEE_CONSTRUCTION', 'PUISSANCE_VEHICULE', 'VALEUR_DU_BIEN']

**Quels sont vos premiers commentaires ? Type de produit ? Périmètre temporel ? Modalités particulières ?**

### Anlayse des caractéristiques du portefeuille

In [105]:
fig = px.histogram(data_set.sort_values('ANNEE_CTR'), x="ANNEE_CTR")
fig.update_xaxes(type='category') #Cette ligne permet de forcer la variable comme variable catégorielle et non numérique

fig.show()

**Réaliser les graphiques pour autres variables présentes dans la base**

In [106]:
#Ecrivez votre code ici
fig = px.histogram(data_set.sort_values('CONTRAT_ANCIENNETE'), x="CONTRAT_ANCIENNETE")
fig.update_xaxes(type='category') #Cette ligne permet de forcer la variable comme variable catégorielle et non numérique

fig.show()

In [107]:
#Ecrivez votre code ici
fig = px.histogram(data_set.sort_values('FREQUENCE_PAIEMENT_COTISATION'), x="FREQUENCE_PAIEMENT_COTISATION")
fig.update_xaxes(type='category') #Cette ligne permet de forcer la variable comme variable catégorielle et non numérique

fig.show()

In [108]:
#Ecrivez votre code ici
fig = px.histogram(data_set.sort_values('GROUPE_KM'), x="GROUPE_KM")
fig.update_xaxes(type='category') #Cette ligne permet de forcer la variable comme variable catégorielle et non numérique

fig.show()

In [109]:
#Ecrivez votre code ici
fig = px.histogram(data_set.sort_values('ZONE_RISQUE'), x="ZONE_RISQUE")
fig.update_xaxes(type='category') #Cette ligne permet de forcer la variable comme variable catégorielle et non numérique

fig.show()

In [110]:
#Ecrivez votre code ici
fig = px.histogram(data_set.sort_values('AGE_ASSURE_PRINCIPAL'), x="AGE_ASSURE_PRINCIPAL")
fig.update_xaxes(type='category') #Cette ligne permet de forcer la variable comme variable catégorielle et non numérique

fig.show()

In [111]:
#Ecrivez votre code ici
fig = px.histogram(data_set.sort_values('GENRE'), x="GENRE")
fig.update_xaxes(type='category') #Cette ligne permet de forcer la variable comme variable catégorielle et non numérique

fig.show()

Un graphique qui décrit de manière plus détaillée la population est la pyramide des âges

In [112]:
#Préparation des données : compter le nombre de femmes et hommes par âge
tmp = data_set[["AGE_ASSURE_PRINCIPAL","GENRE"]].value_counts().to_frame('counts').reset_index()
data_f = tmp[tmp["GENRE"] == "F"]
data_h = tmp[tmp["GENRE"] == "M"]

#Comparaison des âges
list_1=sorted(data_f["AGE_ASSURE_PRINCIPAL"].unique())
list_2=sorted(data_h["AGE_ASSURE_PRINCIPAL"].unique())

print("Eléments dans la liste 2 mais pas dans la liste 1 ")
print(list(set(list_2) - set(list_1)))

print("Eléments dans la liste 1 mais pas dans la liste 2 :")
print(list(set(list_1) - set(list_2)))

Eléments dans la liste 2 mais pas dans la liste 1
[]
Eléments dans la liste 1 mais pas dans la liste 2 :
[np.int64(13)]

In [113]:
# Il faut ajouter l'âge 13 dans la liste 2 (data_h)
data_h = pd.concat([data_h, pd.DataFrame([[13, "M",0]],columns=['AGE_ASSURE_PRINCIPAL', 'GENRE','counts'])], ignore_index=True)

#On ordonne les dataframes
data_h = data_h.sort_values('AGE_ASSURE_PRINCIPAL', ascending = True)
data_f = data_f.sort_values('AGE_ASSURE_PRINCIPAL', ascending = True)

In [114]:
# Graphique
y_age = data_h['AGE_ASSURE_PRINCIPAL']
x_M = data_h['counts']
x_F = data_f['counts'] * -1

In [115]:
fig = gp.Figure()

# Ajout des données H
fig.add_trace(gp.Bar(y= y_age, x = x_M,
                     name = 'Hommes',
                     orientation = 'h'))

# Ajout des données F
fig.add_trace(gp.Bar(y = y_age, x = x_F,
                     name = 'Femmes', orientation = 'h'))

# layout du graphique
fig.update_layout(title = 'Population du portefeuille',
                 title_font_size = 22, barmode = 'relative',
                 bargap = 0.0, bargroupgap = 0,
                 xaxis = {'title': 'Count',
                              'title_font_size': 14},
                  yaxis = {'title': 'Age',
                              'title_font_size': 14}
                 )

fig.show()

**Quels sont vos commentaires ? En particulier sur la sinistralité ?**

**Exercice :** Tracez un graphique permettant de visualiser la distribution des coûts des sinistres

In [116]:
fig = px.histogram(data_set[data_set['CHARGE'] >= 0], x="CHARGE", nbins=50)
fig.update_layout(title="Distribution des coûts des sinistres")
fig.show()

## 5. Retraitements

Une fois la phase d'appropriation du portefeuille passée, il est possible de nettoyer/retraiter la base de données dans le but d'obtenir une base exploitable à la modélisation

### Retraitement des NA

**Quelles possibilités s'offrent à nous ?**

**Implémentez les 3 solutions discutées**

In [117]:
data_retraitee = data_set

# Option 1 : pour la variable "PUISSANCE_VEHICULE"
data_retraitee['PUISSANCE_VEHICULE'] = data_retraitee['PUISSANCE_VEHICULE'].dropna()
data_retraitee.head()

,ANNEE_CTR,CONTRAT_ANCIENNETE,FREQUENCE_PAIEMENT_COTISATION,GROUPE_KM,ZONE_RISQUE,AGE_ASSURE_PRINCIPAL,GENRE,DEUXIEME_CONDUCTEUR,ANCIENNETE_PERMIS,ANNEE_CONSTRUCTION,ENERGIE,EQUIPEMENT_SECURITE,PUISSANCE_VEHICULE,VALEUR_DU_BIEN,NB,CHARGE,EXPO
0,2019,"(-1,0]",ANNUEL,[20000;40000[,B,54,M,False,47,2016.0,ESSENCE,FAUX,NaN,[10000;15000[,0,0.0,0.672131
1,2019,"(-1,0]",ANNUEL,[20000;40000[,B,88,F,True,55,2018.0,DIESEL,VRAI,"(85,96]",[20000;25000[,0,0.0,0.631148
2,2021,"(1,2]",ANNUEL,[0;20000[,D,35,F,True,16,2017.0,ESSENCE,FAUX,"(74,80]",[15000;20000[,0,0.0,0.821918
3,2021,"(2,5]",ANNUEL,[0;20000[,C,46,NaN,False,44,2018.0,ESSENCE,VRAI,"(120,596]",[35000;99999[,0,0.0,0.832877
4,2018,"(2,5]",MENSUEL,[20000;40000[,A,46,F,False,31,2009.0,DIESEL,FAUX,"(66,74]",[10000;15000[,0,0.0,1.000000

In [118]:
#Option 2 : pour les variables (GROUPE_KM,GENRE,
# ANNEE_CONSTRUCTION,VALEUR_DU_BIEN,DEUXIEME_CONDUCTEUR)

data_retraitee["GROUPE_KM"] = data_retraitee["GROUPE_KM"].fillna("[0;20000[")
data_retraitee["GENRE"] = data_retraitee["GENRE"].fillna("Autre")
data_retraitee["ANNEE_CONSTRUCTION"] = data_retraitee["ANNEE_CONSTRUCTION"].fillna("2021")
data_retraitee["VALEUR_DU_BIEN"] = data_retraitee["VALEUR_DU_BIEN"].fillna("Inconnu")
data_retraitee["DEUXIEME_CONDUCTEUR"] = data_retraitee["DEUXIEME_CONDUCTEUR"].fillna("False")

In [119]:
#Option 3 : pour les variables (ZONE_RISQUE,DEUXIEME_CONDUCTEUR)

#Ecrivez votre code ici
data_retraitee["ZONE_RISQUE"] = data_retraitee["ZONE_RISQUE"].fillna("Inconnu")
data_retraitee["DEUXIEME_CONDUCTEUR"] = data_retraitee["DEUXIEME_CONDUCTEUR"].fillna("False")

In [120]:
data_retraitee.head()

,ANNEE_CTR,CONTRAT_ANCIENNETE,FREQUENCE_PAIEMENT_COTISATION,GROUPE_KM,ZONE_RISQUE,AGE_ASSURE_PRINCIPAL,GENRE,DEUXIEME_CONDUCTEUR,ANCIENNETE_PERMIS,ANNEE_CONSTRUCTION,ENERGIE,EQUIPEMENT_SECURITE,PUISSANCE_VEHICULE,VALEUR_DU_BIEN,NB,CHARGE,EXPO
0,2019,"(-1,0]",ANNUEL,[20000;40000[,B,54,M,False,47,2016.0,ESSENCE,FAUX,NaN,[10000;15000[,0,0.0,0.672131
1,2019,"(-1,0]",ANNUEL,[20000;40000[,B,88,F,True,55,2018.0,DIESEL,VRAI,"(85,96]",[20000;25000[,0,0.0,0.631148
2,2021,"(1,2]",ANNUEL,[0;20000[,D,35,F,True,16,2017.0,ESSENCE,FAUX,"(74,80]",[15000;20000[,0,0.0,0.821918
3,2021,"(2,5]",ANNUEL,[0;20000[,C,46,Autre,False,44,2018.0,ESSENCE,VRAI,"(120,596]",[35000;99999[,0,0.0,0.832877
4,2018,"(2,5]",MENSUEL,[20000;40000[,A,46,F,False,31,2009.0,DIESEL,FAUX,"(66,74]",[10000;15000[,0,0.0,1.000000

### Retraitement des valeurs aberrantes

Le traitement de valeurs aberrantes est similaire au traitement des NA. Si le jeu de données contient assez d'individus, il est préférable d'écarter les individus avec des valeurs aberrantes et qui pourraient biaiser l'étude.

**Avez-vous trouvé des valeurs aberrantes ?**  
**Exercice :** Retraitez les valeurs qui vous semblent aberrantes

In [121]:
#Ecrivez votre code ici

### Transformation de l'exposition en exposition journalière

In [122]:
data_retraitee["EXPO"] = data_retraitee["EXPO"].multiply(365)

### Sauvegarde des données

In [123]:
data_retraitee.to_csv("./2_outputs/base_retraitee.csv", index =  False)

## 6. Analyse de la sinistralité

Notre objectif final est de construire un modèle tarifaire. Il convient donc de construire 2 variables qui caractérisent la sinistralité :
* La fréquence de sinistres (NB / EXPO) 
* Le coût moyen (CHARGE / NB)

In [124]:
#Calcul de la fréquence
data_retraitee["FREQ"] = data_retraitee["NB"] / data_retraitee["EXPO"]
data_retraitee["FREQ"] = data_retraitee["FREQ"].fillna(0)

#Calcul du coût moyen
data_retraitee["CM"] = data_retraitee["CHARGE"] / data_retraitee["NB"]
data_retraitee["CM"] = data_retraitee["CM"].fillna(0)

Les modèles tarifaires essayent d'établir un lien entre les variables explicatives et la sinistralité. C'est le travail d'un actuaire comprendre et avoir un regard critique sur les relations trouvées.  
Pour aider l'actuaire dans ce travail, la visualisation des données (FREQ, CM) en fonction des variables explicatives peut être utile.  
  
Dans ce qui suit, nous allons faire cet exercice que sur certaines variables explicatives. Cet exercice peut bien sûr être étendu aux autres variables explicatives.  
**Remarque :** 
*Attention au sens de l'analyse que vous menez. Si on s'intéresse par exemple au coût moyen de la garantie RC, ce dernier n'a pas de dépendance géographique (toute chose égale par ailleurs une victime sera indemnisée à la même hauteur à Lille ou à Marseille).*

 ### Fréquence en fonction de l'âge du conducteur

In [134]:
#Ecrivez votre code ici
freq_by_age = data_retraitee.groupby('AGE_ASSURE_PRINCIPAL').agg({
    'NB': 'sum',
    'EXPO': 'sum'
}).reset_index()

freq_by_age['FREQ'] = freq_by_age['NB'] / freq_by_age['EXPO']
freq_by_age['FREQ'] = freq_by_age['FREQ'].fillna(0)

fig = px.line(freq_by_age, x='AGE_ASSURE_PRINCIPAL', y='FREQ',
              title='Fréquence de sinistres en fonction de l\'âge du conducteur')
fig.update_xaxes(title='Âge du conducteur principal')
fig.update_yaxes(title='Fréquence')
fig.show()

### Fréquence en fonction du genre

In [135]:
#Ecrivez votre code ici
freq_by_genre = data_retraitee.groupby('GENRE').agg({
    'NB': 'sum',
    'EXPO': 'sum'
}).reset_index()

freq_by_genre['FREQ'] = freq_by_genre['NB'] / freq_by_genre['EXPO']
freq_by_genre['FREQ'] = freq_by_genre['FREQ'].fillna(0)

fig = px.scatter(freq_by_genre, x='GENRE', y='FREQ',
              title='Fréquence de sinistres en fonction du genre du conducteur')
fig.update_xaxes(title='Genre du conducteur principal')
fig.update_yaxes(title='Fréquence')
fig.show()

### Fréquence en fonction de la zone de risque

In [127]:
#Ecrivez votre code ici
freq_by_zone_risque = data_retraitee.groupby('ZONE_RISQUE').agg({
    'NB': 'sum',
    'EXPO': 'sum'
}).reset_index()

freq_by_zone_risque['FREQ'] = freq_by_zone_risque['NB'] / freq_by_zone_risque['EXPO']
freq_by_zone_risque['FREQ'] = freq_by_zone_risque['FREQ'].fillna(0)

fig = px.line(freq_by_zone_risque, x='ZONE_RISQUE', y='FREQ',
              title='Fréquence de sinistres en fonction de la zone du risque du conducteur')
fig.update_xaxes(title='Zone du risque du conducteur principal')
fig.update_yaxes(title='Fréquence')
fig.show()

### Fréquence en fonction du carburant

In [136]:
#Ecrivez votre code ici
freq_by_carburant = data_retraitee.groupby('ENERGIE').agg({
    'NB': 'sum',
    'EXPO': 'sum'
}).reset_index()

freq_by_carburant['FREQ'] = freq_by_carburant['NB'] / freq_by_carburant['EXPO']
freq_by_carburant['FREQ'] = freq_by_carburant['FREQ'].fillna(0)

fig = px.scatter(freq_by_carburant, x='ENERGIE', y='FREQ',
              title='Fréquence de sinistres en fonction du carburant du véhicule')
fig.update_xaxes(title='Carburant du véhicule')
fig.update_yaxes(title='Fréquence')
fig.show()

### Coût moyen en fonction du prix

In [129]:
#Ecrivez votre code ici
freq_by_prix = data_retraitee.groupby('VALEUR_DU_BIEN').agg({
    'NB': 'sum',
    'EXPO': 'sum'
}).reset_index()

freq_by_prix['FREQ'] = freq_by_prix['NB'] / freq_by_prix['EXPO']
freq_by_prix['FREQ'] = freq_by_prix['FREQ'].fillna(0)

fig = px.line(freq_by_prix, x='VALEUR_DU_BIEN', y='FREQ',
              title='Fréquence de sinistres en fonction du prix du bien')
fig.update_xaxes(title='Prix du bien')
fig.update_yaxes(title='Fréquence')
fig.show()

### Coût moyen en fonction de l'ancienneté du bien

In [130]:
#Ecrivez votre code ici
freq_by_anciennete = data_retraitee.groupby('CONTRAT_ANCIENNETE').agg({
    'NB': 'sum',
    'EXPO': 'sum'
}).reset_index()

freq_by_anciennete['FREQ'] = freq_by_anciennete['NB'] / freq_by_anciennete['EXPO']
freq_by_anciennete['FREQ'] = freq_by_anciennete['FREQ'].fillna(0)

fig = px.line(freq_by_anciennete, x='CONTRAT_ANCIENNETE', y='FREQ',
              title='Fréquence de sinistres en fonction de l\'ancienneté du contrat')
fig.update_xaxes(title='Ancienneté du contrat')
fig.update_yaxes(title='Fréquence')
fig.show()

### Coût moyen en fonction de l'âge de l'assuré

In [131]:
#Ecrivez votre code ici
freq_by_age = data_retraitee.groupby('CONTRAT_ANCIENNETE').agg({
    'NB': 'sum',
    'EXPO': 'sum'
}).reset_index()

freq_by_age['FREQ'] = freq_by_age['NB'] / freq_by_age['EXPO']
freq_by_age['FREQ'] = freq_by_age['FREQ'].fillna(0)

fig = px.line(freq_by_age, x='CONTRAT_ANCIENNETE', y='FREQ',
              title='Fréquence de sinistres en fonction de l\'ancienneté du contrat')
fig.update_xaxes(title='Ancienneté du contrat')
fig.update_yaxes(title='Fréquence')
fig.show()

### Coût moyen en fonction du genre

In [132]:
#Ecrivez votre code ici